configs:
  n8n-ts-serve:
    content: |
      {"TCP":{"443":{"HTTPS":true}},
      "Web":{"$${TS_CERT_DOMAIN}:443":
          {"Handlers":{"/":
          {"Proxy":"http://127.0.0.1:5678"}}}},
      "AllowFunnel":{"$${TS_CERT_DOMAIN}:443":false}}

volumes: 
  n8n_data:
    name: n8n_data

services:
  n8n-ts:
    image: tailscale/tailscale:latest
    container_name: n8n-ts 
    hostname: n8n
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SERVE_CONFIG=/config/serve.json
      - TS_USERSPACE=true
    configs:
      - source: n8n-ts-serve
        target: /config/serve.json
    cap_add:
      - net_admin
      - sys_module
    volumes:
      - /etc/infras/n8n/tailscale/ts-state:/var/lib/tailscale
    restart: always 

  n8n_app:
    container_name: n8n-app
    build: .
    network_mode: service:n8n-ts
    depends_on:
      - n8n-ts
    security_opt:
      - no-new-privileges:true
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      - N8N_SECURE_COOKIE=false
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - NODE_FUNCTION_ALLOW_EXTERNAL=mermaid
      - N8N_HOST=n8n.hydra-everest.ts.net
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - N8N_RUNNERS_ENABLED=true
      - NODE_ENV=production
      - WEBHOOK_URL=https://n8n.hydra-everest.ts.net:5678
      - GENERIC_TIMEZONE=Australia/Sydney
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_VERSION_NOTIFICATIONS_ENABLED=false
      - N8N_TEMPLATES_ENABLED=true
      - N8N_PROXY_HOPS=0
      - TZ=Australia/Sydney
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=10.10.20.111
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=${DB_POSTGRES_USER}
      - DB_POSTGRESDB_PASSWORD=${DB_POSTGRES_PASSWORD}
    volumes:
      - n8n_data:/home/node/.n8n
      - /etc/infras/n8n/files:/files
